Lesson/javascript
bykovmikhail72/CRT-education pull request #4
Opened 2022-07-30 20:29 UTC by bykovmikhail72

Постарался сделать более или менее качественно:) Буду ждать фидбек.

2022-08-01 15:11 UTC, BubbaCat requested changes

2022-08-01 15:11 UTC, BubbaCat commented on script.js
> +const simpleFunc = () => {
Круто! 
Но давай вместо использования переменных внутри функций, будем передавать их как параметры? то есть:
simpleFunc = (userName) => {
}

2022-08-01 15:11 UTC, BubbaCat commented on script.js
> +const heroes = (data, filter) => {
в названии функции должен быть глагол, чтобы было понятное что она делает. Допустим как было выше: writePersonData

2022-08-01 15:11 UTC, BubbaCat commented on script.js
> +const arrOfKeys = () => {
Супер)
А еще есть метод Object.keys(obj), он сделает тоже самое :)

2022-08-01 15:11 UTC, BubbaCat commented on script.js
> +        const sumAge = newArr.reduce((acc, val) => {
А почему бы не брать сразу возраст тут через val.age? 
Тогда можно будет лишний раз не обходить массив через map

2022-08-01 15:46 UTC, bykovmikhail72 commented on script.js
> +        const sumAge = newArr.reduce((acc, val) => {
Получал undefined и ошибки(
Сделал обходным путем

2022-08-01 15:46 UTC, bykovmikhail72 commented on script.js
> +const arrOfKeys = () => {
Почитаю документацию сегодня)

2022-08-01 15:47 UTC, bykovmikhail72 commented on script.js
> +const heroes = (data, filter) => {
Сделал по аналогии с реакт компонентами, будто бы это компонент)
Замечание учту, спасибо)

2022-08-01 15:49 UTC, bykovmikhail72 commented on script.js
> +const simpleFunc = () => {
Будет учтено)

2022-08-04 16:55 UTC, BubbaCat approved these changes

2022-08-04 16:55 UTC, BubbaCat commented on script.js
> +    const someAge = () => {
Насколько я понимаю по названию функции, age должен был передаваться тут)
а в функции выше только name

2022-08-08 19:09 UTC, merged